dist: xenial
language: ruby
cache: bundler
services:
  - docker
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - jruby-9.1.14.0
  - jruby-9.1.17.0
  - jruby-9.2.10.0
env:
  global:
  - USERNAME=travis
  - PASSWORD=
  - DB_USER=upsert_test
  - DB_PASSWORD=upsert_test
  - DB_NAME=upsert_test
  matrix:
    - DB=postgresql DB_VERSION=postgres:9.4
    - DB=postgresql DB_VERSION=postgres:9.5
    - DB=postgresql DB_VERSION=postgres:9.6
    - DB=postgresql DB_VERSION=postgres:10
    - DB=postgresql DB_VERSION=postgres:11
    - DB=postgresql DB_VERSION=postgres:12
    - DB=postgresql DB_VERSION=postgres:9.4 UNIQUE_CONSTRAINT=true
    - DB=postgresql DB_VERSION=postgres:9.5 UNIQUE_CONSTRAINT=true
    - DB=postgresql DB_VERSION=postgres:9.6 UNIQUE_CONSTRAINT=true
    - DB=postgresql DB_VERSION=postgres:10 UNIQUE_CONSTRAINT=true
    - DB=postgresql DB_VERSION=postgres:11 UNIQUE_CONSTRAINT=true
    - DB=postgresql DB_VERSION=postgres:12 UNIQUE_CONSTRAINT=true
    - DB=mysql DB_VERSION=mysql:5.6
    - DB=mysql DB_VERSION=mysql:5.7
    - DB=mysql DB_VERSION=mysql:8
matrix:
  exclude:
    - rvm: 2.6
      env: DB=postgresql DB_VERSION=postgres:9.4
    - rvm: 2.6
      env: DB=postgresql DB_VERSION=postgres:9.5
    - rvm: 2.6
      env: DB=postgresql DB_VERSION=postgres:9.4 UNIQUE_CONSTRAINT=true
    - rvm: 2.6
      env: DB=postgresql DB_VERSION=postgres:9.5 UNIQUE_CONSTRAINT=true
    - rvm: jruby-9.2.10
      env: DB=postgresql DB_VERSION=postgres:9.4
    - rvm: jruby-9.2.10
      env: DB=postgresql DB_VERSION=postgres:9.5
    - rvm: jruby-9.2.10
      env: DB=postgresql DB_VERSION=postgres:9.4 UNIQUE_CONSTRAINT=true
    - rvm: jruby-9.2.10
      env: DB=postgresql DB_VERSION=postgres:9.5 UNIQUE_CONSTRAINT=true
  allow_failures:
    - env: DB=postgresql DB_VERSION=postgres:12
    - env: DB=postgresql DB_VERSION=postgres:12 UNIQUE_CONSTRAINT=true
before_install:
  - ./travis/run_docker_db.sh
  - bundle --version
  - gem --version
script: ./travis/run_specs.sh
