name: RSpec Tests
on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.2.x, 2.3.x, 2.4.x, 2.5.x, 2.6.x, 2.7.x, 3.0.x, jruby-9.1.x, jruby-9.2.x]
        unique_constraint: ["true", "false"]
        include:
          - db: postgres:9.4
          - db: postgres:9.5
          - db: postgres:9.6
          - db: postgres:10
          - db: postgres:11
          - db: postgres:12
          - db: postgres:13
          - db: mysql:5.6
          - db: mysql:5.7
          - db: mysql:8

    services:
      db:
        image: ${{ matrix.db }}
        env:
          POSTGRES_PASSWORD: upsert_test
          POSTGRES_USER: upsert_test
          POSTGRES_DB: upsert_test
          MYSQL_ROOT_PASSWORD: upsert_test
          MYSQL_DATABASE: upsert_test
          MYSQL_USER: upsert_test
          MYSQL_PASSWORD: upsert_test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      env:
        DB: ${{ matrix.db }}
      run: bundle exec rake
